//status for order status
exports.STATUS_PENDING = 'PENDING';
exports.STATUS_WIP = 'WIP';
exports.STATUS_CANCELLED = 'CANCELLED';
exports.STATUS_COMPLETED = 'COMPLETED';

//house type
exports.TYPE_PRIVATE = 'PRIVATE';
exports.TYPE_FC = 'FREE COMPANY';

//service name
exports.SERVICE_INTERIOR_SMALL = 'INTERIOR SMALL';
exports.SERVICE_INTERIOR_MEDIUM = 'INTERIOR MEDIUM';
exports.SERVICE_INTERIOR_LARGE = 'INTERIOR LARGE';
exports.SERVICE_EXTERIOR_SMALL = 'EXTERIOR SMALL';
exports.SERVICE_EXTERIOR_MEDIUM = 'EXTERIOR MEDIUM';
exports.SERVICE_EXTERIOR_LARGE = 'EXTERIOR LARGE';

//price
exports.PRICE_INTERIOR_SMALL = '6000000';
exports.PRICE_INTERIOR_MEDIUM = '8000000';
exports.PRICE_INTERIOR_LARGE = '12000000';
exports.PRICE_EXTERIOR_SMALL = '300000';
exports.PRICE_EXTERIOR_MEDIUM = '500000';
exports.PRICE_EXTERIOR_LARGE = '800000';